[daemon]
enabled = true
idle_timeout = "365d"

[profiles.agents.secrets]
CPA_API_KEY = { provider = "gopass", value = "agents/cpa1-api-key", env = false }

[providers.gopass]
type = "password-store"

[profiles.postgres.secrets]
POSTGRES_PASSWORD = { provider = "gopass", value = "services/postgres/password" }

[profiles.cpa2.secrets]
DB_PASSWORD = { provider = "gopass", value = "services/cpa2/db-password" }
CLI_PROXY_DB_PASSWORD = { provider = "gopass", value = "services/cpa2/cli-proxy-db-password" }
MANAGEMENT_PASSWORD = { provider = "gopass", value = "services/cpa2/management-password" }
PGSTORE_DSN = { provider = "gopass", value = "services/cpa2/pgstore-dsn" }

[profiles.cpa1.secrets]
DB_PASSWORD = { provider = "gopass", value = "services/cpa1/db-password" }
CLI_PROXY_DB_PASSWORD = { provider = "gopass", value = "services/cpa1/cli-proxy-db-password" }
MANAGEMENT_PASSWORD = { provider = "gopass", value = "services/cpa1/management-password" }
PGSTORE_DSN = { provider = "gopass", value = "services/cpa1/pgstore-dsn" }

[profiles.newt.secrets]
SITE_SECRET= { provider = "gopass", value = "services/newt/site-secret" }

[profiles.friday.secrets]
CPA_API_KEY = { provider = "gopass", value = "agents/cpa1-api-key" }
DISCORD_APPLICATION_ID = { provider = "gopass", value = "services/friday/discord-application-id" }
DISCORD_BOT_TOKEN = { provider = "gopass", value = "services/friday/discord-bot-token" }
DISCORD_PUBLIC_KEY = { provider = "gopass", value = "services/friday/discord-public-key" }
TAILSCALE_AUTH_KEY = { provider = "gopass", value = "services/friday/tailscale-auth-key" }

[profiles.sunday.secrets]
CPA_API_KEY = { provider = "gopass", value = "agents/cpa1-api-key" }
DISCORD_BOT_TOKEN = { provider = "gopass", value = "services/sunday/discord-bot-token" }
