name: fleet-services

include:
  - postgres/compose.yaml
  - cpa1/compose.yaml
  - cpa2/compose.yaml
  - newt/compose.yaml
  - docker-in-docker/compose.yaml
  - friday/compose.yaml
  - sunday/compose.yaml
